build: false
image: Visual Studio 2017

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan nose
  - conan install cmake_installer/3.7.2@conan/stable -g=virtualrunenv
  - activate_run.bat

test_script:
  - nosetests .
