build: false
image: Visual Studio 2017

environment:
  PYTHON: "C:\\Python37"
  PYTHON_VERSION: "3.7.5"
  PYTHON_ARCH: "32"

install:
  - set PATH=%PYTHON%/Scripts/;%PYTHON%;%PATH%
  - pip.exe install conan nose

test_script:
  - nosetests . -A "not cmake39"
  - nosetests . -A "cmake39"
